### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by cashaffer** [OpenDSA/OpenDSA#162]
We should investigate switching to Python 3. If this is practical, then we should do the update.

**Comment by sublime09** [comment]
### Issue progress will be published to this branch: https://github.com/OpenDSA/OpenDSA/tree/python3

- @SAMHEO already ran 2to3.py to do the many quick fixes. 
- Sphinx library for generating docs seems to be the main issue
- Default installed Sphinx is **v1.2.2** from 2014.  Latest Sphinx at the moment is **v2.4.3** !!!
- Default vagrant machine (Trusty64) of Dev-Stack is Ubuntu 14
- Ubuntu 14 apt-get install for python3 automatically goes to python3.4.  Hmmm...
- Py3.4 support was only added in Sphinx **v1.3b1** !!! (see sphinx patch notes) 

Right now, the aim is to get python 3.4 working.  If later versions of python are not supported by the machine, then 3.4 is the best we can hope for.  Once 3.4 is working, then we can experimentally try out newer versions of python like 3.8.  Focusing on the known-supported python version first is a good idea though.  

We are upgrading our target from sphinx 1.2 to sphinx 1.4 since py3.4 is supported there.  We don't want to jump to sphinx2.4 at the moment because major feature updates tend to break projects and we want to immediately know if breaks happen because of sphinx upgrades or because of python upgrades.  Upgrading to sphinx 2.4 is a possibility once our main work here is done.  

- Note: We may look into the Dev-Stack repo's [python3.8 branch](https://github.com/OpenDSA/OpenDSA-DevStack/tree/python3.8).  It seems simply using wget, and .configure to directly install py3.8 without help from apt was attempted.  No idea if it worked out though.

**Comment by sublime09** [comment]
I came across a decision point recently:  **Should the python3 virtual environment activation be automatic or manual for OpenDSA developers**? Manual means that devs have to learn to use the pyVenv; devs have to remember to enable the pyVenv; and devs could accidentally install many pip packages to their system's python install (not the pyVenv).  Automatic means that _how_ python is being run is more hidden, which could frustrate debugging efforts; devs may not even know that pyVenv is being used; and devs may never learn how to use the pyVenv and the benefits it has.  

At this moment I am choosing **Manual**.  I have several reminders for devs to activate the pyVenv when using make.  The error message they receive when using python without the Venv directs them to use the Venv.

**Comment by sublime09** [comment]
My most recent commit revamps the fundamental Makefile of OpenDSA.  It now builds the python Virtual Environment, installs the pip requirements, and checks that the pyVenv is being used to build the EBooks.  Several helpful targets have been added such as: `venv, clean-venv, python, pipList, pyReqs, Webserver` .  The only thing it does not do is activate the pyVenv.

**Comment by sublime09** [comment]
**Sphinx 2.4.4 is working**.  It seems that the make pipeline was dependent on a 'websupport.js' file that was removed in Sphinx2.0 according to their change notes.   However, it seems OpenDSA never uses it.  There's zero mentions of that filename in any other files of OpenDSA.  But we should be wary, since it is mentioned in OpenDSA-LTI .  If it is needed, we can simply take a copy of it from an older commit.

I recently did a **big merge** of the master branch into the python3 branch, to keep them closer in sync and be up to date with everyone else's work.  Seems to have gone fairly smoothly.  

The Makefile has be refined some more.  Now adding a new book just means adding a name to the `BOOKS` variable.  Unique recipes and targets are still present for more configuration options of making eBooks.  And there is now a default make target that attempts to find a JSON config so that the Makefile doesn't _have_ to be updated every new person.  

So far I have the eBook generated by `make Test` giving zero errors, and zero warnings!  I can find errors if I hunt around and generate other books though.  The `SimpleDemo` book warns that some "TODO directives" of the rst files are undefined.  But perhaps this is incomplete work, so it is expected?  The very large `Everything` eBook gives many of the same warnings, and a few others.  But all of these books finish being created without a critical error!  

I feel the time is getting close to merge with master.  Do you agree @cashaffer ?  I will work on OpenDSA-DevStack a bit in the meantime

**Comment by sublime09** [comment]
I have now merged all of this work into the master branch: 705df8d56e0e56b2fd4279becb6db227145dd4f6

Hopefully everyone is able to adjust to the minor dev workspace changes, and we can close this issue soon!
