### ISSUE TITLE
KA summary exercise randomization algorithm

### ISSUE THREAD

**Issue by cashaffer** [OpenDSA/OpenDSA#283]
For summary exercises, the KA framework selects the next exercise at random from its available list (perhaps using weights). We need support for flagging some exercises as "one time only". Once a student has successfully completed that exercise, it should not be eligible for coming up again while the student is still working on proficiency for the exercise.

**Comment by cashaffer** [comment]
Also, at least the new version of the framework stops generating exercises after it has done 10.

**Comment by hosamshahin** [comment]
In the below blog post, John Resig (Developer at Khan Academy) wrote up about how random exercise generation works in the new Khan Academy exercise framework.﻿

http://ejohn.org/blog/random-khan-exercises/#postcomment

**Comment by kyuhankoh** [comment]
This article makes more sense than the current mechanism, and I don't understand why they changed it. Currently, problemNum and jumpNum are set to 1, actually as we'd like to set. 
I think that the problem comes from the bin number, 200, the number of possible exercises. We don't have possible 200 exercises, so if we update this number to 15 or something, then we have to update the prime number list, and it causes some problem since it's too small, only four prime numbers. 
I think if we are able to set proper seed values, it would be possible to set the exercise order.

**Comment by cashaffer** [comment]
This article is 4 years old. They are constantly working on the mechanism for deciding which exercise to serve next. Their context has changed a lot as well. They now typically first generate a small  (3-4) collection of (infinitely parameterizeable) problems to serve, and then generate a stream out of that. The also want to be able to reproduce the problem stream for a given student (i.e., recover the initial seed).

**Comment by kyuhankoh** [comment]
I didn't know this article is 4 years old, and I found even the old ODSA-Khanexercise did not follow the mechanism in this blog.

**Comment by cashaffer** [comment]
I think this is successfully implemented.
