### ISSUE TITLE
Compiled html pages contain odsaStyle.css while it should be odsaStyle-min.css

### ISSUE THREAD

**Issue by hosamshahin** [OpenDSA/OpenDSA#285]

**Comment by acbart** [comment]
Should I be hard coding a rule to rename odsaStyle.css in the post-processor? Or should it come in more naturally somewhere outside of my part of the pipeline?

**Comment by cashaffer** [comment]
I don't know how the other CSS files are included. For some reason, unlike all of the other CSS files, odsaStyle gets included (on a separate line) as odsaStyle.css instead of odsaStyle-min.css. I assumed that they all got handled in the same way, but I guess this one is being treated differently. Does Hosam know?

**Comment by cashaffer** [comment]
Done. Closing
