### ISSUE TITLE
Arrange permission to use our LTI provider with VT Canvas installation

### ISSUE THREAD

**Issue by cashaffer** [OpenDSA/OpenDSA#300]
In theory, we have to get permission for canvas.vt.edu installation to communicate with "foreign" LTI providers. We understand that this involves some light code review to spot check security issues, etc.

In practice, this might be a moot point. We have already demonstrated creating a course and populating it with our content from our LTI provider, on both the VT test site AND the VT live site. So maybe they are not enforcing any security check? The danger is that they might cut us off unexpectedly at some point.

**Comment by acbart** [comment]
I don't think they're keeping it closed currently, but we could indeed be cut off any time. They mentioned that for BlockPy, they don't really mind if we're just using it in our course (for now), but if we have plans of getting it site-wide then we absolutely need to go through their check. Not a huge deal since I don't think other courses will use BlockPy much, but the extra incentive is that if we pass their test now, it may be easier to pass bigger security checks down the road - VT will be able to vouch for us as an LTI provider, and other schools might follow suit.

So I'd see it as a relatively low priority but still important task. You don't want some VT lawyer to decide that ODSA is a security risk and have it yanked mid-semester, after all.

**Comment by cashaffer** [comment]
I have initiated the check process. I told Bob Edmison where our LTI provider server is, and gave him the URL here. We'll see what happens.

**Comment by cashaffer** [comment]
I was told before Christmas that we are good to go. Surprisingly, when I was visiting TLOS and they showed me about connecting external resources, OpenDSA was already on the list!

Closing.
