### ISSUE TITLE
glob_ff_options support

### ISSUE THREAD

**Issue by cashaffer** [OpenDSA/OpenDSA#345]
A new compiler option has been added to support frames. The GUI compilation settings needs to be updated to support this option (and to do the compilation correctly when it is turned on).

**Comment by cashaffer** [comment]
During compilation of the book, we still get the following spurious message:

WARNING: Missing "glob_ff_options", using default values instead.

**Comment by jwonderly** [comment]
I haven't pushed the changes to production yet, but I can do that now. So if you are testing a config that was generated by the GUI tool, that is probably why.

If you are testing a config file from the config folder, it looks like none of those have been updated to include the "glob_ff_options" settings, so that would be why the error is printing. I will update those config files to include glob_ff_options settings.

**Comment by cashaffer** [comment]
Thanks! This does beg the (somewhat philosophical) question: Should every config file need to explicitly list every parameter, even when they are irrelevant to that book? If the default is "false", maybe we should be able to leave it out without a warning?

**Comment by jwonderly** [comment]
I have updated the configuration files and pushed the updates to production. This includes the update to the GUI configuration tool.

To your point, I think it would probably be better if there aren't warning messages printed about missing settings that aren't relevant anyway. I can put this on my ToDo list.

**Comment by cashaffer** [comment]
Sounds good.

**Comment by cashaffer** [comment]
This appears to be completed. I'm not seeing the warning.
