### ISSUE TITLE
Server communications error in PointerEX1PRO

### ISSUE THREAD

**Issue by cashaffer** [OpenDSA/OpenDSA#346]
This is a KA exercise, and the exercise itself seems to work fine. But when compiled into a Canvas course (see for example the CS2 public offering at https://canvas.instructure.com/courses/1503223/assignments/10395776), this exercise shows "Current score: 0 out of NaN" above the body of the exercise, and working the exercise returns the standard misleading error message: "This page is out of date. You need to refresh, but don't worry, you haven't lost progress. If you think this is a mistake, tell us."

Besides fixing the exercise issue itself, perhaps we can give a better error message?

**Comment by jwonderly** [comment]
I have worked on this a little bit in the external_ex_fix branches of the OpenDSA and OpenDSA-LTI repositories. As I said in my email a while ago, the issue is that the way external exercises were originally implemented in OpenDSA, it was assumed they would be the only gradable thing in the section, but that is no longer necessarily true. In this case, the CodeWorkout exercise was included in the same section as a KA exercise. The result of this was the KA exercise was silently ignored, and so no database record was made for it, thus making it impossible to track attempts and scores.

I have a fix that allows for external exercises (such as CodeWorkout) to share a section with other gradable resources, but I have run into an issue when testing it out: for some reason scores aren't being recorded for CodeWorkout exercises. I am working on debugging it and I think I should be able to figure it out soon.

If not, then an easier "fix" would be to just move the KA exercise into it's own section.

**Comment by cashaffer** [comment]
Looks like there are only two sections that mix Code Workout with other gradable exercises. I will split these up.
