### ISSUE TITLE
Dictionary BST implementation is buggy

### ISSUE THREAD

**Issue by heatherleaf** [OpenDSA/OpenDSA#433]
The code in `SourceCode/Java/Binary/BSTDict.java` contains errors, and won't work.

You store pairs `(k,e)` in a normal BST:
```
  public void insert(Comparable k, Object e) {
    theBST.insert(new KVPair(k, e));
  }
```

When you try to find a key `k`, you just call the normal BST find on the key. But the BST contains pairs, so `k` will never be found:
```
  public Object find(Comparable k) {
    Object temp = theBST.find(k);
    if (temp == null) { return temp; }
    else { return ((KVPair)temp).value() };
  }
```

(The same for the method `remove`)

**Comment by cashaffer** [comment]
I just double-checked that this does indeed work correctly, and I have made a push to update the test file to explicitly check the find operation.

The basic answer is: The KVPair is smart enough to search on the key. So the BST find takes the key and returns the KVPair, and then BSTDict pulls the value from the pair to return to its caller.

I do acknowledge that that the compilation throws a lot of warnings, because this code was written before Comparable was templated in Java.

**Comment by heatherleaf** [comment]
Ah, I see. Sorry for alerting:)
